---
ansible_user: admin
ansible_ssh_private_key_file: ~/.ssh/id_rsa
ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_become_method: sudo
ansible_python_interpreter: /usr/bin/python3
