---
- name: Retrieve status of VM
  command: virsh list --all --name
  register: vm_list
  changed_when: false

- name: Create a new VM
  block:
  - name: Ensure VM disk image is removed
    file:
      path: '{{ vm_images_directory }}/{{ vm_name }}.qcow2'
      state: absent

  - name: Install VM
    command: >
      virt-install
        --connect qemu:///system
        --virt-type kvm
        --name {{ vm_name }}
        --vcpus {{ vm_vcpus }}
        --memory {{ vm_memory }}
        --cpu host-passthrough,cache.mode=passthrough
        --network bridge=br0,mac={{ vm_mac }},model=virtio
        --disk path={{ vm_images_directory }}/{{ vm_name }}.qcow2,size={{ vm_disksize }},cache=none,bus=virtio
        --location {{ vm_images_directory }}/{{ vm_system_installer }}
        --initrd-inject {{ vm_images_directory }}/ks.cfg
        --extra-args 'ks=file:/ks.cfg hostname={{ vm_hostname }} console=tty0 console=ttyS0,115200n8'
        --os-variant centos8
        --graphics none
        --noautoconsole
        --wait

  - name: Setup VM for autostart
    command: virsh autostart {{ vm_name }}

  - name: Wait for VM to power up and become reachable
    wait_for:
      host: '{{ vm_hostname }}'
      port: 22
      delay: 4
      sleep: 4

  - name: Optimise VM guest
    command: tuned-adm profile virtual-guest
    delegate_to: '{{ vm_hostname }}'
    changed_when: false
  when: vm_name not in vm_list.stdout
