---
- name: Provision QEMU/KVM hypervisor hosts
  hosts: all
  become: yes

  tasks:
  - name: Install required system repos
    dnf:
      name: '{{ required_system_repos }}'
      state: present

  - name: Upgrade to latest stable LT kernel
    dnf:
      name: kernel-lt
      enablerepo: elrepo-kernel
      state: present
    register: kernel_upgrade

  - name: Post kernel upgrade tasks 
    block:
    - name: Reboot host after a kernel upgrade
      reboot:

    - name: Remove unused kernel packages
      dnf:
        name:
        - kernel-core
        - kernel-tools
        state: absent
    when: kernel_upgrade.changed

  - name: Update system packages to latest
    dnf:
      name: '*'
      exclude:
      - kernel*
      update_only: yes
      state: latest

  - name: Install required system packages
    dnf:
      name: '{{ required_system_packages }}'
      state: present

  - name: Enable and start up libvirtd daemon
    systemd:
      name: libvirtd
      enabled: true
      state: started

  - name: Optimise system for hosting VMs
    command: tuned-adm profile virtual-host
    changed_when: false

  - name: Copy network configuration
    copy:
      src: files/vhosts/network/
      dest: /etc/sysconfig/network-scripts/
      mode: 0644
    notify: restart_networks      

  - name: Create directory for cloud images
    file:
      path: '{{ cloud_directory }}'
      state: directory
      mode: 0755

  - name: Copy cloud image used in guest VMs
    copy:
      src: '{{ cloud_image_source_path }}/{{ cloud_image }}'
      dest: '{{ cloud_directory }}'
      mode: 0644
      force: no

  - name: Disable SELinux and install core packages in cloud image
    command: >
      virt-customize
        --add {{ cloud_directory }}/{{ cloud_image }}
        --run-command '[ -f /etc/selinux/config ] && sed -i s/^SELINUX=.*$/SELINUX=disabled/ /etc/selinux/config'
        --install python3
        --update
    changed_when: false

  - name: Shrink cloud image
    command: >
      virt-sparsify
        --in-place {{ cloud_directory }}/{{ cloud_image }}
        --quiet
    changed_when: false

  - name: Clean package repo caches
    command:
      cmd: dnf clean all
      warn: false
    changed_when: false

  handlers:
  - name: Restart Network Manager
    systemd:
      name: NetworkManager
      state: restarted
    listen: restart_networks

  - name: Bring up physical interface eno1
    command: nmcli con up filename /etc/sysconfig/network-scripts/ifcfg-eno1
    changed_when: false
    listen: restart_networks

  - name: Bring up bridge interface br0
    command: nmcli con up filename /etc/sysconfig/network-scripts/ifcfg-br0 
    changed_when: false
    listen: restart_networks
