---
- name: Provision QEMU/KVM hypervisor hosts
  hosts: all
  become: yes

  tasks:
  - name: Install required system repos
    dnf:
      name: '{{ required_system_repos }}'
      state: present

  - name: Update system packages to latest
    dnf:
      name: '*'
      exclude:
      - kernel*
      update_only: yes
      state: latest

  - name: Install required system packages
    dnf:
      name: '{{ required_system_packages }}'
      state: present

  - name: Enable and start up libvirtd daemon
    systemd:
      name: libvirtd
      enabled: true
      state: started

  - name: Optimise system for hosting VMs
    command: tuned-adm profile virtual-host
    changed_when: false

  - name: Copy network configurations
    copy:
      src: files/vhosts/network/
      dest: /etc/NetworkManager/system-connections/
      mode: 0600
    notify: restart_networks      

  - name: Create directory for cloud images
    file:
      path: '{{ cloud_directory }}'
      state: directory
      mode: 0755

  - name: Copy cloud image used in guest VMs
    copy:
      src: '{{ cloud_image_source_path }}/{{ cloud_image }}'
      dest: '{{ cloud_directory }}'
      mode: 0644
      force: no

  - name: Disable SELinux in cloud image and install required packages
    command: >
      virt-customize
        --add {{ cloud_directory }}/{{ cloud_image }}
        --run-command '[ -f /etc/selinux/config ] && sed -i s/^SELINUX=.*$/SELINUX=disabled/ /etc/selinux/config'
        --install tuned
    changed_when: false

  - name: Clean package repo caches
    command:
      cmd: dnf clean all
    changed_when: false

  handlers:
  - name: Restart Network Manager
    systemd:
      name: NetworkManager
      state: restarted
    listen: restart_networks

  - name: Bring up bridge interface
    command: nmcli con up br0 
    changed_when: false
    listen: restart_networks

  - name: Bring up physical interface
    command: nmcli con up enp88s0
    changed_when: false
    listen: restart_networks
