---
- name: Update system packages on vhosts
  hosts: all
  become: yes

  tasks:
    - name: Update system packages skipping excluded ones
      dnf:
        name: '*'
        exclude:
          - kernel*
        update_only: yes
        state: latest
